# Generated by Django 3.2.4 on 2025-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_repairrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairrequest',
            name='address',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='customer_name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=100),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='problem',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='product_name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=100),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='serial_number',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=100),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='status',
            field=models.CharField(choices=[('estimate', 'ประเมิน'), ('in_progress', 'ดำเนินการซ่อม'), ('done', 'ซ่อมเสร็จ'), ('returned', 'ส่งคืน')], db_collation='utf8mb4_unicode_ci', default='estimate', max_length=20),
        ),
    ]
