# Generated by Django 3.2.4 on 2025-05-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20250508_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='occupation',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=100, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150),
        ),
        migrations.AlterField(
            model_name='scrums',
            name='task',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrums',
            name='task_description',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrumtitles',
            name='lists',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issued_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issued_to',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='created_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='issued_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='issued_to',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_name',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='phone_number',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='received_by',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=50, null=True),
        ),
    ]
